version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:20.10.1

jobs:
    docker:
        parameters:
            with_publish:
                type: boolean
                default: false
        executor: docker
        steps:
            - checkout
            - setup_remote_docker:
                version: 17.09.0-ce
            - run:
                name: Build
                command: |
                    apk add --no-cache git
                    git fetch --tags
                    docker build -t app .
            - when:
                condition: <<parameters.with_publish>>
                steps:
                    - run:
                        name: Publish Latest & Tagged
                        command: |
                            echo $CONTAINER_REGISTRY_PASS | docker login ghcr.io -u $CONTAINER_REGISTRY_USER --password-stdin
                            docker tag app $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/discord-automod:latest
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/discord-automod:latest
                            docker tag app $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/discord-automod:$(git describe --tags --abbrev=0)
                            docker push $CONTAINER_REGISTRY_URL/$CONTAINER_REGISTRY/discord-automod:$(git describe --tags --abbrev=0)
                            
workflows:
    version: 2
    cicd:
        jobs:
            - docker:
                name: Build & Publish
                with_publish: true